#!/bin/bash

#Custermize this for your application
#APPLICATION_FILE_PATH=vff

#Parameters
PRODUCT_HOME=/Library/__PRODUCT__/__VERSION__

echo "Post installation process started"
if grep -Fxq 'export PATH="'${PRODUCT_HOME}':$PATH"' ~/.bash_profile
then
    # code if found
    echo 'Already Exists'
else
    # code if not found
    echo 'export PATH="'${PRODUCT_HOME}':$PATH"' >> ~/.bash_profile
fi
source ~/.bash_profile

#Change permissions in home directory
#echo "Change permissions in product home"
#cd ${PRODUCT_HOME}
#chmod -R 755 .
#[ -d /usr/local/bin ] || mkdir /usr/local/bin
#
##Add application shortcut to /usr/local/bin
#rm -f /usr/local/bin/__PRODUCT__-__VERSION__
#ln -s ${PRODUCT_HOME}/${APPLICATION_FILE_PATH} /usr/local/bin/__PRODUCT__-__VERSION__
echo "Post installation process finished"
